
---

spring:
  application:
    name: product-service
  cloud:
    config:
      uri: http://localhost:8090
  h2:
    consoles:
      enable: true

server:
  port: 8081

jpa:
  show-sql: true
  hibernate:
    ddl-auto: update